import Head from "next/head";
import Image from "next/image";
import { Config } from "../config";
import fetch from "isomorphic-fetch";
import PageWrapper from "../components/Global/PageWrapper";
import Link from "next/link";

export default function Home({ categories }) {
  console.log("categories: ", categories);
  return (
    <>
      {" "}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageWrapper>
        <main>
          <h2>I am the Home Page</h2>
          {categories.map((category, index) => {
            return (
              <Link
                key={index}
                href={"/categories/[slug]"}
                as={`/categories/${category.slug}`}
              >
                <a>
                  <li>{category.name}</li>
                </a>
              </Link>
            );
          })}
        </main>
      </PageWrapper>
    </>
  );
}

export async function getStaticProps() {
  const result = await fetch(`${Config.apiUrl}/wp-json/wp/v2/categories`);
  const categories = await result.json();
  return {
    props: {
      categories: categories,
    },
  };
}
